version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: family-tree-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-family_tree}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - family-tree-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: family-tree-backend
    restart: always
    environment:
      DB_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-secret}@postgres:5432/${DB_NAME:-family_tree}?schema=public
      JWT_SECRET: ${JWT_SECRET:-super_secret}
      OTP_EXPIRY: ${OTP_EXPIRY:-600}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - family-tree-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: family-tree-frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
      NEXT_PUBLIC_SOCKET_URL: ws://backend:3001
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - family-tree-network

networks:
  family-tree-network:
    driver: bridge

volumes:
  postgres-data:
